### PR TITLE
1/3 make TestClient public to allow mocking and overriding baseURL

### PR DESCRIPTION
**Pull request by seantcanavan**
I can't access baseURL in my mock go-athenahealth client and I can't call `testClient` because it's private and defined in a test file.

Because I can't reach baseURL - my local unit tests that instantiate a HTTP Test Client always try to call either the preview URL or the prod URL because the `h.baseURL` is set privately everywhere.

The crucial lines that I don't have access to are:

```
func testClient(h http.HandlerFunc) (*HTTPClient, *httptest.Server) {
...
...
	ts := httptest.NewServer(h)

	athenaClient := NewHTTPClient(ts.Client(), testPracticeID, testAPIKey, testAPISecret).
		WithTokenProvider(&testTokenProvider{}).
		WithTokenCacher(&testTokenCacher{})

	athenaClient.baseURL = ts.URL // there's no public access to this that I can find and `testClient` is a test function
```

### CODE REVIEW

**Comment by seantcanavan** [comment]
@dillonstreator i might've missed a better way to access `baseURL` but this seemed to be the cleanest way I could think of without making `baseURL` public which could cause unintentional bugs.

this is the biggest priority now for us on the copilotiq side as I can't write clean and reusable tests without access to the client's baseURL so I've renamed the PRs accordingly

**Comment by seantcanavan** [comment]
> @seantcanavan How are you testing and how are you mocking the go-athenahealth client? Your calling code should accept an interface that uses a mock client during testing. The mock client shouldn't call Athena. The baseURL shouldn't need to be modified and the testClient shouldn't need to be exposed.

we have something like this:

github.com/CopilotIQ/common/athena_utils.go
```
var AthenaClient = NewRealAthenaClient()

func NewRealAthenaClient() {
   // standard setup here
}

func NewMockAthenaClient() {
   // mock client setup here
}
```

github.com/CopilotIQ/project/athena.go
```
func ScheduleAppointment()
{
...
common.AthenaClient.BookAppointment()
...
}

github.com/CopilotIQ/project/athena_test.go
```
...
func TestScheduleAppointment(t *testing.T) {
    common.AthenaClient = NewMockAthenaClient()
}
...
```

I guess I was hoping to short cut creating the mock and all the tests for the mock? If I can set the baseURL I won't have to 1) create a mock of the client interface and 2) test those mock functions and 3) very easily re-use the same client that y'all use for your tests. I fear creating my own mock would duplicate a ton of functionality within the tests and the existing codebase thanks to `testClient(...)`. 

I see this as an access problem to `baseURL` however I might be seeing this from a different perspective. Any new code I have to write has to be tested (obviously) so re-using the eleanorhealth test client makes sense in my book since it doesn't make real http calls either and can be easily configured with not only the test files in this repo but also custom handlers / files on our end as well.

**Comment by dillonstreator** [comment]
@seantcanavan thank you for sharing your general implementation and testing approach.

Dependency injection, having your application code rely on interfaces, and a couple defacto testing packages can improve your ability to test and mock.

```go
package athena

import "github.com/eleanorhealth/go-athenahealth/athenahealth"

type Client interface {
     athenahealth.Client
}
```

```go
package consumingpackage

func ScheduleAppointment(athenaClient athena.Client) error {
    //...
    athenaClient.BookAppointment()
    //...
    return nil
}
```

Between [`stretchr/testify`](https://github.com/stretchr/testify#mock-package)’s mock package and [`vektra/mockery`](https://github.com/vektra/mockery), you can generate mock implementations based purely on your interface definition
https://github.com/stretchr/testify#mock-package
https://github.com/vektra/mockery

Your test would now become:
```go
// ...
func TestScheduleAppointment(t *testing.T) {
     athenaClient = athena.NewMockClient(t)
     athenaClient.On("BookAppointment", arg1, arg2).Return(errors.New("...")).Once()
     ScheduleAppointment(athenaClient)
}
// ...
```

I don't think we should pursue exposing the internal testing helpers.

**Comment by seantcanavan** [comment]
@dillonstreator understood. thanks for taking the time to explain that - i sincerely appreciate it. I will take a look at those packages and adapt our strategy accordingly. i believe I understand the gist of what's going on there though.

**Pull request closed without merging**
